services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      mysql:
        condition: service_healthy
      dynamodb-local:
        condition: service_started

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pmy-secret-pw"]
      interval: 20s
      timeout: 10s
      retries: 10

volumes:
  mysql_data:
